config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/normflow-plugintest:
      branch: mlflow-intertwin-demo
      repo: https://github.com/PalomoIFCA/normflow-plugintest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-platinum-maltese.sh
        container: qc.acc_skinny-brown-tang
  QC.Doc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tasty-copper-cattle.sh
        container: qc.doc_homey-salmon-lion
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-violet-slug.sh
        container: qc.doc_dorky-wheat-shrew
      github.com/PalomoIFCA/normflow-plugintest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.beady-cobalt-chamois.sh
        container: qc.doc_baggy-cobalt-raccoon
  QC.Lic:
    repos:
      github.com/PalomoIFCA/normflow-plugintest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.lousy-eggplant-retriever.sh
        container: qc.lic_nippy-cobalt-centipede
  QC.Met:
    repos:
      github.com/PalomoIFCA/normflow-plugintest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.clammy-indigo-chicken.sh
        container: qc.met_zippy-copper-caracal
  QC.Sec:
    repos:
      github.com/PalomoIFCA/normflow-plugintest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.sloppy-salmon-hedgehog.sh
        container: qc.sec_smelly-khaki-tiger
  QC.Sty:
    repos:
      github.com/PalomoIFCA/normflow-plugintest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scaly-apricot-meerkat.sh
        container: qc.sty_beady-persimmon-discus
      github.com/PalomoIFCA/normflow-plugintest hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.greasy-puce-zorse.sh
        container: qc.sty_woozy-periwinkle-terrier
      github.com/PalomoIFCA/normflow-plugintest jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-sapphire-fish.sh
        container: qc.sty_lovely-chartreuse-quetzal
  QC.Uni:
    repos:
      github.com/PalomoIFCA/normflow-plugintest commands:
        commands:
        - /usr/bin/env sh .sqa/script.shaky-sangria-wolverine.sh
        container: qc.uni_muzzy-violet-bobcat
  QC.Ver:
    repos:
      github.com/PalomoIFCA/normflow-plugintest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.squirrely-cobalt-buzzard.sh
        container: qc.ver_gummy-cinnamon-caiman
timeout: 5400
