config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/normflow-plugintest:
      branch: mlflow-intertwin-demo
      repo: https://github.com/PalomoIFCA/normflow-plugintest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.baggy-aqua-dunker.sh
        container: qc.acc_foggy-tan-barb
  QC.Doc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.squeaky-ochre-salamander.sh
        container: qc.doc_slimy-smalt-saola
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-burgundy-dachshund.sh
        container: qc.doc_shaky-purple-shrimp
      github.com/PalomoIFCA/normflow-plugintest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-denim-greyhound.sh
        container: qc.doc_tacky-khaki-bordeaux
  QC.Lic:
    repos:
      github.com/PalomoIFCA/normflow-plugintest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-violet-sheepdog.sh
        container: qc.lic_flaky-salmon-markhor
  QC.Met:
    repos:
      github.com/PalomoIFCA/normflow-plugintest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.randy-beige-salamander.sh
        container: qc.met_clammy-emerald-kangaroo
  QC.Sec:
    repos:
      github.com/PalomoIFCA/normflow-plugintest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-rose-gopher.sh
        container: qc.sec_jumpy-apricot-mule
  QC.Sty:
    repos:
      github.com/PalomoIFCA/normflow-plugintest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-teal-bandicoot.sh
        container: qc.sty_hazy-champagne-flamingo
      github.com/PalomoIFCA/normflow-plugintest hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gimpy-corn-sheep.sh
        container: qc.sty_baggy-thistle-malamute
      github.com/PalomoIFCA/normflow-plugintest jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cinnamon-caiman.sh
        container: qc.sty_cranky-burgundy-shrimp
  QC.Uni:
    repos:
      github.com/PalomoIFCA/normflow-plugintest commands:
        commands:
        - /usr/bin/env sh .sqa/script.nippy-lemon-mongrel.sh
        container: qc.uni_wheezy-salmon-budgerigar
  QC.Ver:
    repos:
      github.com/PalomoIFCA/normflow-plugintest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wheezy-magnolia-chimpanzee.sh
        container: qc.ver_foggy-teal-harrier
timeout: 5400
