config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: feature/Ophidia
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/PalomoIFCA/normflow-plugintest:
      branch: mlflow-intertwin-demo
      repo: https://github.com/PalomoIFCA/normflow-plugintest
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-aquamarine-quokka.sh
        container: qc.acc_tacky-dandelion-lion
  QC.Doc:
    repos:
      github.com/PalomoIFCA/normflow-plugintest find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.hazy-lime-stingray.sh
        container: qc.doc_lumpy-ruby-penguin
      github.com/PalomoIFCA/normflow-plugintest git:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-magnolia-eagle.sh
        container: qc.doc_nippy-chartreuse-chimpanzee
      github.com/PalomoIFCA/normflow-plugintest markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-grey-spoonbill.sh
        container: qc.doc_ugly-indigo-buffalo
  QC.Lic:
    repos:
      github.com/PalomoIFCA/normflow-plugintest licensee:
        commands:
        - /usr/bin/env sh .sqa/script.slimy-dandelion-mayfly.sh
        container: qc.lic_sickly-lemon-sheepdog
  QC.Met:
    repos:
      github.com/PalomoIFCA/normflow-plugintest cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-thistle-butterfly.sh
        container: qc.met_boozy-grey-dragonfly
  QC.Sec:
    repos:
      github.com/PalomoIFCA/normflow-plugintest bandit:
        commands:
        - /usr/bin/env sh .sqa/script.smelly-rust-angora.sh
        container: qc.sec_cranky-bronze-ocelot
  QC.Sty:
    repos:
      github.com/PalomoIFCA/normflow-plugintest flake8:
        commands:
        - /usr/bin/env sh .sqa/script.freaky-lemon-capuchin.sh
        container: qc.sty_sunny-cerise-rhinoceros
      github.com/PalomoIFCA/normflow-plugintest hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.gummy-olive-setter.sh
        container: qc.sty_lumpy-lilac-sheepdog
      github.com/PalomoIFCA/normflow-plugintest jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-firebrick-wolf.sh
        container: qc.sty_greasy-viridian-shrew
  QC.Uni:
    repos:
      github.com/PalomoIFCA/normflow-plugintest commands:
        commands:
        - /usr/bin/env sh .sqa/script.hasty-azure-lionfish.sh
        container: qc.uni_paltry-red-raccoon
  QC.Ver:
    repos:
      github.com/PalomoIFCA/normflow-plugintest get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.stealthy-harlequin-spoonbill.sh
        container: qc.ver_cloudy-plum-crocodile
timeout: 5400
